### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by tomvo** [hsiaosiyuan0/vue-dropdown#2]
Wanted to check out your plugin, seems the demo doesn't work?

**Comment by larsmars** [comment]
FYI path: http://vue-demo.hsiaosiyuan.com/#/dropdown

**Comment by RoanBrand** [comment]
Still not working for me. And trying to run locally I see this:
![image](https://user-images.githubusercontent.com/14920090/36379934-22676308-1589-11e8-8eb9-8710267dce99.png)

**Comment by bihongbin3027** [comment]
有默认选中这个功能吗？
